### ISSUE TITLE
TASK 2: Make predictions on test images using open-source libraries available for OCR

### ISSUE THREAD

**Issue by Chinmay-jain767** [Artificial-Brix/BRIX-OCR#1]
Make a jupyter notebook, in which you can write the codes to do OCR on the images given in  the test_images folder

- About the task : For better understanding, please have a look here: [TASK 2](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#tasks-to-resolve)
- contribution : For making a contribution please have look here: [Contribute](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#how-to-contribute)

Since there are multiple algorithms for making the predictions, multiple contributors can participate in it and make their own notebook as a contribution.

**Comment by preyam2002** [comment]
Can I start working on this issue?

**Comment by Chinmay-jain767** [comment]
Yes Sure

**Comment by Smruti2002** [comment]
I have also started working on the issue

**Comment by Smruti2002** [comment]
Can you assign me this?

**Comment by Chinmay-jain767** [comment]
Keras-OCR and easy-OCR are done. Try using other libraries mentioned in the README file.

**Comment by Chinmay-jain767** [comment]
@preyam2002 and @Smruti2002 have resolved the issue.
