### ISSUE TITLE
TASK 0: Find the open-source training dataset for OCR engine training and add the drive link in the README file

### ISSUE THREAD

**Issue by Chinmay-jain767** [Artificial-Brix/BRIX-OCR#3]
Find the open-source available datasets for training the OCR engine (minimum 3) and add it to your drive and then add the drive link in the dataset section of the README file.

- About the task: For better understanding, please have a look here: [TASK 0](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#tasks-to-resolve)
- contribution : For making a contribution please have a look here: [Contribute](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#how-to-contribute)
    

Since a person can find different datasets, multiple contributors can participate in it and submit their links as a contribution.

**Comment by preyam2002** [comment]
Task 0 completed

**Comment by I-am-sayantan** [comment]
> Task 0 completed

Thanks for your contribution to this issue.
