### ISSUE TITLE
TASK 1: Making the dataset of Newspaper,Posters and Sheets and add them to their respective folder

### ISSUE THREAD

**Issue by Chinmay-jain767** [Artificial-Brix/BRIX-OCR#4]
# TASK 1 :Building the test dataset:

Add 50 images in each folder of Posters, Newspapers and Sheets to make a contribution. A sample for each of them has been given in their respective folders.

- About the task: For better understanding, please have a look here: [TASK 1](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#tasks-to-resolve)
- contribution : For making a contribution please have a look here: [Contribute](https://github.com/Artificial-Brix/BRIX-OCR/blob/main/README.md#how-to-contribute)
    
Since a person can make different datasets, multiple contributors can participate in it and submit it as a contribution.

**Comment by Smruti2002** [comment]
hey @I-am-sayantan @Chinmay-jain767 ! 
can you assign me this ?

**Comment by Smruti2002** [comment]
Completed task 1 issue
